// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CheckUpdate() {
  return window['go']['main']['App']['CheckUpdate']();
}

export function GetSettings() {
  return window['go']['main']['App']['GetSettings']();
}

export function SaveSettings(arg1) {
  return window['go']['main']['App']['SaveSettings'](arg1);
}
