// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function CheckUpdate():Promise<string>;

export function GetSettings():Promise<main.Settings>;

export function SaveSettings(arg1:string):Promise<void>;
